kind: Deployment
apiVersion: apps/v1
metadata:
  name: edc-proxy-deployment-staging
  namespace: marketplace
  labels:
    app: edc-proxy-staging
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edc-proxy-staging
  template:
    metadata:
      labels:
        app: edc-proxy-staging
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
        runAsGroup: 1001
      imagePullSecrets:
        - name: marketplace-registry-pull-secrets
      containers:
        - name: edc-proxy-staging
          image: registry.atosresearch.eu:18519/edc-proxy:${IMAGE_TAG}
          imagePullPolicy: Always
          env:
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
          envFrom:
            - secretRef:
                name: edc-proxy-staging-secrets
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: edc-proxy-service-staging
  namespace: marketplace
  labels:
    app: edc-proxy-staging
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: edc-proxy-staging
  ports:
    - name: edc-proxy-port
      port: 8080
      targetPort: 8080
      protocol: TCP